[theme]
base = "light"
primaryColor = "#FF69B4"
backgroundColor = "#E6E6FA"
secondaryBackgroundColor = "#D8BFD8"
textColor = "#4B3832"
linkColor = "#1E90FF"
codeBackgroundColor = "#FFE4E1"
font = "Arial, sans-serif"
codeFont = "monospace"
headingFont = "sans-serif"
baseRadius = "10px"
borderColor = "#D3D3D3"
showWidgetBorder = true
baseFontSize = 16
showSidebarBorder = true
