[theme]
base = "light"
primaryColor = "#AD4746"
#backgroundColor = "#FFDFE0"
backgroundColor = "#FFF6F7"
#secondaryBackgroundColor = "#FFE8E9"
secondaryBackgroundColor = "#FFDFE0"
textColor = "#4B3832"
linkColor = "#1E90FF"
codeBackgroundColor = "#FFF2CC"
font = "Arial, sans-serif"
codeFont = "monospace"
headingFont = "sans-serif"
baseRadius = "10px"
borderColor = "#D3D3D3"
showWidgetBorder = true
baseFontSize = 16
showSidebarBorder = true

[server]
maxUploadSize = 300
